[build]
  publish = "/"        # Tu carpeta principal donde est√° el index.html
  functions = "netlify/functions"  # Indica la CARPETA, no el archivo

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200